---
title: "Riley's Personal Analysis"
output: html_document
---

Quantitative Descriptive Analysis

```{r}
wineData = read.csv("extracted data.csv", header=TRUE)
summary(wineData)
```
```{r}
library(reshape2)
library(ggplot2)
wineData$Cultivar = c(rep("Mencia",20),rep("Alicante Bouschet",10))
wineMelt = melt(wineData[,-c(1,2)],
                id.vars = "Cultivar",
                variable.name = "Measure")
ggplot(data=wineMelt, aes(x=Measure, y=value)) +
  geom_boxplot(aes(col=Measure), notch = FALSE) +
  scale_y_log10() +
  facet_grid(~Cultivar) +
  ylab("Values")
```

```{r}
apply(wineData[1:20,3:25],2,shapiro.test)
```

First try PCA on whole dataset, look for cultivar separation.

```{r}
wineDataVariables = wineData[,3:25]


wineDataPCA = as.matrix(wineDataVariables) %*% as.matrix(prcomp(wineDataVariables, center = TRUE, scale = TRUE)$rotation)

summary(prcomp(wineDataVariables, center = TRUE, scale = TRUE))
# first 5 PCs have stdev>1, drop rest
wineDataPCA = wineDataPCA[,1:5]
summary(wineDataPCA)
wineDataPCADF = as.data.frame(wineDataPCA)
apply(wineDataPCADF[1:20,],2,shapiro.test)

```
```{r}
PCAMahalanobis = mahalanobis(wineDataPCADF,center = colMeans(wineDataPCADF),cov = cov(wineDataPCADF))
PCAMahalanobis
surprise = pchisq(PCAMahalanobis,df=5,lower.tail = FALSE)
surprise
surpriseFull = ifelse(surprise <= 0.01, "Very Surprising",
                      ifelse(surprise <= 0.05, "Surprising",
                             ifelse(surprise <= 0.1, "Slightly Surprising", surprise)))
surpriseFull
```
```{r}
PCAFullMenciaMahal = mahalanobis(wineDataPCADF, center=colMeans(wineDataPCADF[1:20,]), cov=cov(wineDataPCADF[1:20,]))
PCAFullMenciaMahal
pchisq(PCAFullMenciaMahal, df=5, lower.tail=FALSE)
```
```{r}
PCAFullAlicanteMahal = mahalanobis(wineDataPCADF, center=colMeans(wineDataPCADF[21:30,]), cov=cov(wineDataPCADF[21:30,]))
PCAFullAlicanteMahal
pchisq(PCAFullAlicanteMahal, df=5, lower.tail=FALSE)
```

```{r}
# PCs from  full dataset, mahalanobis from individual cultivar distributions excluding the individual observation

surpriseFullExc = rep(NA,30)
mahalFullExc = rep(NA,30)
for(i in 1:20){
  wineTemp = wineDataPCADF[1:20,][-i,]
  muTemp = colMeans(wineTemp)
  covTemp = cov(wineTemp)
  mahalFullExc[i] = mahalanobis(wineDataPCADF[i,], center = muTemp, cov=covTemp)
  surpriseFullExc[i] = pchisq(mahalFullExc[i], df=5, lower.tail=FALSE)
}
for(i in 21:30){
  wineTemp = wineDataPCADF[21:30,][-i,]
  muTemp = colMeans(wineTemp)
  covTemp = cov(wineTemp)
  mahalFullExc[i] = mahalanobis(wineDataPCADF[i,], center = muTemp, cov=covTemp)
  surpriseFullExc[i] = pchisq(mahalFullExc[i], df=5, lower.tail=FALSE)
}
mahalFullExc
surpriseFullExc <= 0.1
```

```{r}
# mahalanobis with PCA assuming no grouping in data

mahal1Group = mahalanobis(wineDataPCADF, center=colMeans(wineDataPCADF), cov = cov(wineDataPCADF))
mahal1Group
surprise1Group = pchisq(mahal1Group, df=5, lower.tail=FALSE)
surprise1GroupWords = ifelse(surprise1Group <= 0.01, "Very Surprising",
                             ifelse(surprise1Group <= 0.05, "Surprising",
                                    ifelse(surprise1Group <=0.1, "Slightly Surprising", round(surprise1Group,5))))
surprise1GroupWords
```

```{r}
# identifying variables that load mainly on PC2
rot = as.data.frame(prcomp(wineDataVariables,center=TRUE,scale=TRUE)$rotation)[,1:5]
max.col(abs(rot))
rot$PC2[max.col(abs(rot))==2]
rownames(rot[c(5:8,23),])
```
```{r}
# checking if sample T25 is significantly different from mencia at all
mahalanobis(wineDataPCADF[25,], center = colMeans(wineDataPCADF[1:20,]), cov = cov(wineDataPCADF[1:20,]))
pchisq(12.66538,df=5,lower.tail = FALSE)
```
```{r}
#  checking if samples 23-26 are inconsistent with other AB
library(dplyr)
mahalTemp = mahalanobis(wineDataPCADF[23:26,], center = colMeans(wineDataPCADF[c(21,22,27:30),]), cov = cov(wineDataPCADF[c(21,22,27:30),])) 

pchisq(mahalanobis(wineDataPCADF[23:26,], center = colMeans(wineDataPCADF[c(21,22,27:30),]), cov = cov(wineDataPCADF[c(21,22,27:30),])) ,df=5,lower.tail=FALSE)

mahalTemp ; pchisq(mahalTemp, df=5, lower.tail = FALSE)
```

```{r}
#  plot of PC2
plot(wineDataPCADF$PC2,
     1:30,
     col = c(rep("red",20),rep("blue",10)),
     pch = as.character(c(1:9,0)))
```


