---
title: "Riley's Personal Analysis v2"
output: html_document
---

```{r}
wineData = read.csv("~/STAT394-Group-Project/extracted data.csv", header=TRUE)
summary(wineData)
```
```{r}
library(reshape2)
library(ggplot2)
wineData$Cultivar = c(rep("Mencia",20),rep("Alicante Bouschet",10))
wineMelt = melt(wineData[,-c(1,2)],
                id.vars = "Cultivar",
                variable.name = "Measure")
ggplot(data=wineMelt, aes(x=Measure, y=value)) +
  geom_boxplot(aes(col=Measure), notch = FALSE) +
  scale_y_log10() +
  facet_grid(~Cultivar) +
  ylab("Values")
```

```{r}
apply(wineData[1:20,3:25],2,shapiro.test)
```

First try PCA on whole dataset, look for cultivar separation.

```{r}
wineDataVariables = wineData[,3:25]


wineDataPCA = prcomp(wineDataVariables, center = TRUE, scale = TRUE)$x

summary(prcomp(wineDataVariables, center = TRUE, scale = TRUE))
# first 5 PCs have stdev>1, drop rest
wineDataPCA = wineDataPCA[,1:5]
summary(wineDataPCA)
wineDataPCADF = as.data.frame(wineDataPCA)
apply(wineDataPCADF[1:20,],2,shapiro.test)

```
```{r}
# mahalanobis to find surprising obs from model assuming no groups
PCAMahalanobis = mahalanobis(wineDataPCADF,center = colMeans(wineDataPCADF),cov = cov(wineDataPCADF))
PCAMahalanobis
surprise = pchisq(PCAMahalanobis,df=5,lower.tail = FALSE)
surprise
surpriseFull = ifelse(surprise <= 0.01, "Very Surprising",
                      ifelse(surprise <= 0.05, "Surprising",
                             ifelse(surprise <= 0.1, "Slightly Surprising", round(surprise,4))))
surpriseFull
```
```{r}
# check if AB obs are consistent with M distribution
PCAFullMenciaMahal = mahalanobis(wineDataPCADF, center=colMeans(wineDataPCADF[1:20,]), cov=cov(wineDataPCADF[1:20,]))
PCAFullMenciaMahal
surpriseMencia = pchisq(PCAFullMenciaMahal, df=5, lower.tail=FALSE)
surpriseMenciaWords = ifelse(surpriseMencia <= 0.01, "Very Surprising",
                      ifelse(surpriseMencia <= 0.05, "Surprising",
                             ifelse(surpriseMencia <= 0.1, "Slightly Surprising", round(surpriseMencia,4))))
surpriseMenciaWords
surpriseMencia
```
```{r}
# check if M obs are consistent with AB distribution
PCAFullAlicanteMahal = mahalanobis(wineDataPCADF, center=colMeans(wineDataPCADF[21:30,]), cov=cov(wineDataPCADF[21:30,]))
PCAFullAlicanteMahal
surpriseAlicante = pchisq(PCAFullAlicanteMahal, df=5, lower.tail=FALSE)
surpriseAlicanteWords = ifelse(surpriseAlicante <= 0.01, "Very Surprising",
                      ifelse(surpriseAlicante <= 0.05, "Surprising",
                             ifelse(surpriseAlicante <= 0.1, "Slightly Surprising", round(surpriseAlicante,4))))
surpriseAlicanteWords
surpriseAlicante
```

```{r}
# PCs from  full dataset, mahalanobis from individual cultivar distributions excluding the individual observation

surpriseCulExc = rep(NA,30)
mahalCulExc = rep(NA,30)
for(i in 1:20){
  wineTemp = wineDataPCADF[1:20,][-i,]
  muTemp = colMeans(wineTemp)
  covTemp = cov(wineTemp)
  mahalCulExc[i] = mahalanobis(wineDataPCADF[i,], center = muTemp, cov=covTemp)
  surpriseCulExc[i] = pchisq(mahalCulExc[i], df=5, lower.tail=FALSE)
}
for(i in 21:30){
  iAdj = i - 20
  wineTemp = wineDataPCADF[21:30,][-iAdj,]
  muTemp = colMeans(wineTemp)
  covTemp = cov(wineTemp)
  mahalCulExc[i] = mahalanobis(wineDataPCADF[i,], center = muTemp, cov=covTemp)
  surpriseCulExc[i] = pchisq(mahalCulExc[i], df=5, lower.tail=FALSE)
}
mahalCulExc
surpriseCulExcWords =  ifelse(surpriseCulExc <= 0.01, "Very Surprising",
                      ifelse(surpriseCulExc <= 0.05, "Surprising",
                             ifelse(surpriseCulExc <= 0.1, "Slightly Surprising", round(surpriseCulExc,4))))
surpriseCulExcWords
round(surpriseCulExc,6)
```

```{r}
#  playing around with plots
library(ggplot2)
library(ggcorrplot)
library(GGally)
plot(wineDataPCADF$PC1,
     wineDataPCADF$PC2,
     col = c(rep("red",20),rep("blue",10)),
     pch = c(LETTERS,letters[1:4]))
```

```{r}
# playing with graphs for within AB subgroup
plot(wineDataPCADF[21:30,]$PC1,
     wineDataPCADF[21:30,]$PC2,
     col = c("green",rep("black",5),rep("green",4)),
     pch = as.character(c(1:9,0)))
```

```{r}
# mahalanobis analysis of subclusters within AB (without exclusion) (all PCs) (PCs from full dataset)
wineAB1 = wineDataPCADF[c(21,27:30),]
wineAB2 = wineDataPCADF[22:26,]
muAB1 = colMeans(wineAB1)
muAB2 = colMeans(wineAB2)
sigAB1 = cov(wineAB1)
sigAB2 = cov(wineAB2)
# mahalanobis(wineAB1,center = muAB1, cov = sigAB1)
# samples too small to calculate mahalanobis distance on 5 variables. PC5 shows no clustering, drop and reattempt
```


```{r}
# mahalanobis analysis of subclusters within AB (without exclusion) (PC1-4) (PCs from full dataset)
wineAB1 = wineDataPCADF[c(21,27:30),1:4]
wineAB2 = wineDataPCADF[22:26,1:4]
muAB1 = colMeans(wineAB1)
muAB2 = colMeans(wineAB2)
sigAB1 = cov(wineAB1)
sigAB2 = cov(wineAB2)
mahalanobis(wineAB1,center = muAB1, cov = sigAB1)
# still too many variables for number of obs, gives constant dM. repeat with just PC1,PC2
```


```{r}
# mahalanobis analysis of subclusters within AB (without exclusion) (PC1-3) (PCs from full dataset)
wineAB1 = wineDataPCADF[c(21,27:30),1:3]
wineAB2 = wineDataPCADF[22:26,1:3]
muAB1 = colMeans(wineAB1)
muAB2 = colMeans(wineAB2)
sigAB1 = cov(wineAB1)
sigAB2 = cov(wineAB2)
mahalanobis(wineAB1,center = muAB1, cov = sigAB1)
mahalanobis(wineAB2,center = muAB1, cov = sigAB1)
mahalanobis(wineAB2,center = muAB2, cov = sigAB2)
mahalanobis(wineAB1,center = muAB2, cov = sigAB2)

pchisq(mahalanobis(wineAB1,center = muAB1, cov = sigAB1), df=2, lower.tail = FALSE)
pchisq(mahalanobis(wineAB2,center = muAB1, cov = sigAB1), df=2, lower.tail = FALSE)
pchisq(mahalanobis(wineAB2,center = muAB2, cov = sigAB2), df=2, lower.tail = FALSE)
pchisq(mahalanobis(wineAB1,center = muAB2, cov = sigAB2), df=2, lower.tail = FALSE)

```

```{r}
# mahalanobis analysis of subclusters within AB (without exclusion) (PC1-2) (PCs from full dataset)
wineAB1 = wineDataPCADF[c(21,27:30),1:2]
wineAB2 = wineDataPCADF[22:26,1:2]
muAB1 = colMeans(wineAB1)
muAB2 = colMeans(wineAB2)
sigAB1 = cov(wineAB1)
sigAB2 = cov(wineAB2)
mahalanobis(wineAB1,center = muAB1, cov = sigAB1)
mahalanobis(wineAB2,center = muAB1, cov = sigAB1)
mahalanobis(wineAB2,center = muAB2, cov = sigAB2)
mahalanobis(wineAB1,center = muAB2, cov = sigAB2)


pchisq(mahalanobis(wineAB1,center = muAB1, cov = sigAB1), df=2, lower.tail = FALSE)
pchisq(mahalanobis(wineAB2,center = muAB1, cov = sigAB1), df=2, lower.tail = FALSE)
pchisq(mahalanobis(wineAB2,center = muAB2, cov = sigAB2), df=2, lower.tail = FALSE)
pchisq(mahalanobis(wineAB1,center = muAB2, cov = sigAB2), df=2, lower.tail = FALSE)

```
```{r}
# factor loadings
prcomp(wineDataVariables, center = TRUE, scale = TRUE)$rotation[,1:2]
library(ggbiplot)
library(rlang)
ggbiplot(prcomp(wineDataVariables, center = TRUE, scale = TRUE), obs.scale = 1, var.scale = 1, alpha = 0.1)
```

```{r}
# mahalanobis analysis of subclusters within AB (with exclusion) (PC1-2) (PCs from full dataset)
wineAB1 = wineDataPCADF[c(21,27:30),1:2]
wineAB2 = wineDataPCADF[22:26,1:2]
wineAB = wineDataPCADF[21:30,1:2]

surpFromAB1Exc = rep(NA,10)
surpFromAB2Exc = rep(NA,10)
ind = 0
for(i in c(1,7:10)){
  ind = ind + 1
  wineAB1Temp = wineAB1[-ind,]
  iTemp = i + 20
  mahalAB1Temp = mahalanobis(wineAB1[ind,], center = colMeans(wineAB1Temp), cov = cov(wineAB1Temp))
  mahalAB2Temp = mahalanobis(wineAB1[ind,], center = colMeans(wineAB2), cov = cov(wineAB2))
  surpFromAB1Exc[i] = pchisq(mahalAB1Temp, df=2, lower.tail=FALSE)
  surpFromAB2Exc[i] = pchisq(mahalAB2Temp, df=2, lower.tail = FALSE)
}

ind = 0
for(i in 2:6){
  ind = ind + 1
  wineAB2Temp = wineAB2[-ind,]
  iTemp = i + 20
  mahalAB1Temp = mahalanobis(wineAB2[ind,], center = colMeans(wineAB1), cov = cov(wineAB1))
  mahalAB2Temp = mahalanobis(wineAB2[ind,], center = colMeans(wineAB2Temp), cov = cov(wineAB2Temp))
  surpFromAB1Exc[i] = pchisq(mahalAB1Temp, df=2, lower.tail=FALSE)
  surpFromAB2Exc[i] = pchisq(mahalAB2Temp, df=2, lower.tail = FALSE)
}
surpFromAB1Exc
surpFromAB2Exc

surpFromAB1ExcWords =  ifelse(surpFromAB1Exc <= 0.01, "Very Surprising",
                      ifelse(surpFromAB1Exc <= 0.05, "Surprising",
                             ifelse(surpFromAB1Exc <= 0.1, "Slightly Surprising", round(surpFromAB1Exc,4))))

surpFromAB2ExcWords =  ifelse(surpFromAB2Exc <= 0.01, "Very Surprising",
                      ifelse(surpFromAB2Exc <= 0.05, "Surprising",
                             ifelse(surpFromAB2Exc <= 0.1, "Slightly Surprising", round(surpFromAB2Exc,4))))

surpFromAB1ExcWords
surpFromAB2ExcWords
```

```{r}
# mahalanobis analysis of subclusters within AB (with exclusion) (PC1-2) (PCs from full dataset) (switch 21 into cluster 2)
wineAB1 = wineDataPCADF[27:30,1:2]
wineAB2 = wineDataPCADF[21:26,1:2]
wineAB = wineDataPCADF[21:30,1:2]

surpFromAB1Exc = rep(NA,10)
surpFromAB2Exc = rep(NA,10)
ind = 0
for(i in 7:10){
  ind = ind + 1
  wineAB1Temp = wineAB1[-ind,]
  iTemp = i + 20
  mahalAB1Temp = mahalanobis(wineAB1[ind,], center = colMeans(wineAB1Temp), cov = cov(wineAB1Temp))
  mahalAB2Temp = mahalanobis(wineAB1[ind,], center = colMeans(wineAB2), cov = cov(wineAB2))
  surpFromAB1Exc[i] = pchisq(mahalAB1Temp, df=2, lower.tail=FALSE)
  surpFromAB2Exc[i] = pchisq(mahalAB2Temp, df=2, lower.tail = FALSE)
}

ind = 0
for(i in 1:6){
  ind = ind + 1
  wineAB2Temp = wineAB2[-ind,]
  iTemp = i + 20
  mahalAB1Temp = mahalanobis(wineAB2[ind,], center = colMeans(wineAB1), cov = cov(wineAB1))
  mahalAB2Temp = mahalanobis(wineAB2[ind,], center = colMeans(wineAB2Temp), cov = cov(wineAB2Temp))
  surpFromAB1Exc[i] = pchisq(mahalAB1Temp, df=2, lower.tail=FALSE)
  surpFromAB2Exc[i] = pchisq(mahalAB2Temp, df=2, lower.tail = FALSE)
}
surpFromAB1Exc
surpFromAB2Exc

surpFromAB1ExcWords =  ifelse(surpFromAB1Exc <= 0.01, "Very Surprising",
                      ifelse(surpFromAB1Exc <= 0.05, "Surprising",
                             ifelse(surpFromAB1Exc <= 0.1, "Slightly Surprising", round(surpFromAB1Exc,4))))

surpFromAB2ExcWords =  ifelse(surpFromAB2Exc <= 0.01, "Very Surprising",
                      ifelse(surpFromAB2Exc <= 0.05, "Surprising",
                             ifelse(surpFromAB2Exc <= 0.1, "Slightly Surprising", round(surpFromAB2Exc,4))))

surpFromAB1ExcWords
surpFromAB2ExcWords
```

Results write-up sections

```{r}
# PCA
PCs = prcomp(wineDataVariables, center = TRUE, scale = TRUE)
screeplot(PCs,type = "lines") +
  abline(h=1, col="red")
```

```{r}
# Shapiro-Wilk test of PC1-5 aggregate and by cultivar
aggShap = rep(NA,5)
menShap = rep(NA,5)
abShap = rep(NA,5)
for(i in 1:5){
  aggShap[i] = shapiro.test(wineDataPCADF[,i])$p.value
  menShap[i] = shapiro.test(wineDataPCADF[1:20,i])$p.value
  abShap[i] = shapiro.test(wineDataPCADF[21:30,i])$p.value
}
shapDF = data.frame(Component = c("PC1","PC2","PC3","PC4","PC5"), Aggregate = aggShap, Mencia = menShap, AlicanteBouschet = abShap)
colnames(shapDF)[4] = "Alicante Bouschet"

for(i in 1:5){
  for(j in 2:4){
    charTemp = as.character(round(as.numeric(shapDF[i,j]),4))
    shapDF[i,j] = ifelse(shapDF[i,j] <= 0.01, paste0(charTemp," ***"),
                        ifelse(shapDF[i,j] <= 0.05, paste0(charTemp, " **"),
                               ifelse(shapDF[i,j] <=0.1, paste0(charTemp, " *"),
                                      charTemp)))
  }
}
pander(shapDF)
```


```{r}
# graphical of PCs, full dataset
plot(wineDataPCADF$PC1,
     wineDataPCADF$PC2,
     col = c(rep("red",20),rep("blue",10)),
     lwd = 3) + text(wineDataPCADF$PC1+0.1, wineDataPCADF$PC2-0.2, wineData$Sample, cex = 0.5)
# ggplot(wineDataPCADF, aes(x=PC1,y=PC2)) +
#   geom_point(colour = c(rep("red",20),rep("blue",10))) +
#   geom_text(aes(x=PC1,y=PC2, label = wineData$Sample, cex=0.5))
```


```{r}
# surprising results for mahalanobis: full model, cultivar split, cultivar split with exclusion
library(pander)
presFullModel = rep(NA,30)
presMenInc = rep(NA,30)
presABInc = rep(NA,30)
presSplitExc = rep(NA,30)
for(i in 1:30){
  if(surprise[i] < 0.0001){
    presFullModel[i] = "< 0.0001 ***"
  } else if(surprise[i] <= 0.01){
    presFullModel[i] = paste0(round(surprise[i],4)," ***")
  } else if(surprise[i] <= 0.05){
    presFullModel[i] = paste0(round(surprise[i],4)," **")
  } else if(surprise[i] <= 0.1){
    presFullModel[i] = paste0(round(surprise[i],4)," *")
  } else {
    presFullModel[i] = as.character(round(surprise[i],4))
  }
  if(surpriseMencia[i] < 0.0001){
    presMenInc[i] = "< 0.0001 ***"
  } else if(surpriseMencia[i] <= 0.01){
    presMenInc[i] = paste0(round(surpriseMencia[i],4)," ***")
  } else if(surpriseMencia[i] <= 0.05){
    presMenInc[i] = paste0(round(surpriseMencia[i],4)," **")
  } else if(surpriseMencia[i] <= 0.1){
    presMenInc[i] = paste0(round(surpriseMencia[i],4)," *")
  } else {
    presMenInc[i] = as.character(round(surpriseMencia[i],4))
  }
  if(surpriseAlicante[i] < 0.0001){
    presABInc[i] = "< 0.0001 ***"
  } else if(surpriseAlicante[i] <= 0.01){
    presABInc[i] = paste0(round(surpriseAlicante[i],4)," ***")
  } else if(surpriseAlicante[i] <= 0.05){
    presABInc[i] = paste0(round(surpriseAlicante[i],4)," **")
  } else if(surpriseAlicante[i] <= 0.1){
    presABInc[i] = paste0(round(surpriseAlicante[i],4)," *")
  } else {
    presABInc[i] = as.character(round(surpriseAlicante[i],4))
  }
  if(surpriseCulExc[i] < 0.0001){
    presSplitExc[i] = "< 0.0001 ***"
  } else if(surpriseCulExc[i] <= 0.01){
    presSplitExc[i] = paste0(round(surpriseCulExc[i],4)," ***")
  } else if(surpriseCulExc[i] <= 0.05){
    presSplitExc[i] = paste0(round(surpriseCulExc[i],4)," **")
  } else if(surpriseCulExc[i] <= 0.1){
    presSplitExc[i] = paste0(round(surpriseCulExc[i],4)," *")
  } else {
    presSplitExc[i] = as.character(round(surpriseCulExc[i],4))
  }
}
mahalTable = data.frame(sample = wineData$Sample, fullModel = presFullModel, menciaInc = presMenInc, abInc = presABInc, splitExc = presSplitExc)
mahalTable$splitExc = gsub("2e-04","0.0002",mahalTable$splitExc)
colnames(mahalTable) = c("Sample","Full Dataset","Mencia","Alicante Bouschet","Cultivar Excluding Sample")
pander(mahalTable)
```

```{r}
# graph PC1-2 AB split
plot(wineDataPCADF[21:30,]$PC1,
     wineDataPCADF[21:30,]$PC2,
     col = c("green",rep("black",5),rep("green",4)),
     pch = as.character(c(1:9,0)))
```

```{r}
# mahalanobis AB PC1-3 without exclusion
presCluster1 = rep(NA,10)
presCluster2 = rep(NA,10)

wineAB1 = wineDataPCADF[c(21,27:30),1:3]
wineAB2 = wineDataPCADF[22:26,1:3]
muAB1 = colMeans(wineAB1)
muAB2 = colMeans(wineAB2)
sigAB1 = cov(wineAB1)
sigAB2 = cov(wineAB2)

clus1from1surp = pchisq(mahalanobis(wineAB1,center = muAB1, cov = sigAB1), df=2, lower.tail = FALSE)
clus2from1surp = pchisq(mahalanobis(wineAB2,center = muAB1, cov = sigAB1), df=2, lower.tail = FALSE)
clus2from2surp = pchisq(mahalanobis(wineAB2,center = muAB2, cov = sigAB2), df=2, lower.tail = FALSE)
clus1from2surp = pchisq(mahalanobis(wineAB1,center = muAB2, cov = sigAB2), df=2, lower.tail = FALSE)

clus1Surp = c(clus1from1surp[1],clus2from1surp,clus1from1surp[2:5])
clus2Surp = c(clus1from2surp[1],clus2from2surp,clus1from2surp[2:5])



for(i in 1:10){
  if(clus1Surp[i] < 0.0001){
    presCluster1[i] = "< 0.0001 ***"
  } else if(clus1Surp[i] <= 0.01){
    presCluster1[i] = paste0(round(clus1Surp[i],4)," ***")
  } else if(clus1Surp[i] <= 0.05){
    presCluster1[i] = paste0(round(clus1Surp[i],4)," **")
  } else if(clus1Surp[i] <= 0.1){
    presCluster1[i] = paste0(round(clus1Surp[i],4)," *")
  } else {
    presCluster1[i] = as.character(round(clus1Surp[i],4))
  }
  if(clus2Surp[i] < 0.0001){
    presCluster2[i] = "< 0.0001 ***"
  } else if(clus2Surp[i] <= 0.01){
    presCluster2[i] = paste0(round(clus2Surp[i],4)," ***")
  } else if(clus2Surp[i] <= 0.05){
    presCluster2[i] = paste0(round(clus2Surp[i],4)," **")
  } else if(clus2Surp[i] <= 0.1){
    presCluster2[i] = paste0(round(clus2Surp[i],4)," *")
  } else {
    presCluster2[i] = as.character(round(clus2Surp[i],4))
  }
}
ABDF = data.frame(Sample = wineData$Sample[21:30], Cluster1 = presCluster1, Cluster2 = presCluster2)
pander(ABDF)
```


